import { mkdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, normalize, relative } from "node:path";
import type { LintContext } from "./lint-context.ts";
import {
  configuredIndexPath,
  expectedFolderIndexName,
  listDir,
  pathExists,
  walkFiles,
} from "./lint-helpers.ts";

export function checkRootMarkdown(context: LintContext): void {
  if (context.isExternalOverlay) return;

  for (const entry of listDir(context.root, ".")) {
    const path = entry;
    if (!path.toLowerCase().endsWith(".md")) continue;
    if (!context.allowedRootMarkdown.has(path)) {
      context.add(
        "error",
        "root-markdown",
        "Keep the project root clean: move Markdown documents to analysis/, wiki/, decisions/, or docs/.",
        path,
      );
    }
  }
}

export function checkAnalysisLayout(context: LintContext): void {
  if (!context.analysisGovernanceEnabled) return;

  const analysisRoot = context.config.analysis.root || "analysis";
  if (!pathExists(context.root, analysisRoot)) return;

  const indexPath = configuredIndexPath(context.config.analysis.indexPath, analysisRoot);
  ensureFolderIndex(context, indexPath, analysisRoot, "Analysis Index", "Document", "analysis");

  for (const entry of listDir(context.root, analysisRoot)) {
    const path = join(analysisRoot, entry);
    const stat = statSync(join(context.root, path));

    if (isGeneratedGovernanceIndex(context, path)) continue;
    if (!context.config.analysis.allowMarkdownAtRoot && stat.isFile() && entry.toLowerCase().endsWith(".md")) {
      context.add("error", "analysis-root-file", `Do not leave Markdown files directly under ${analysisRoot}/.`, path);
    }

    if (stat.isDirectory() && context.allowedAnalysisDirs.size > 0 && !context.allowedAnalysisDirs.has(entry)) {
      context.add(
        "warning",
        "analysis-unknown-dir",
        `${analysisRoot}/ folder is not declared by the current taxonomy.`,
        path,
      );
    }
  }
}

export function checkIndexNamingConvention(context: LintContext): void {
  const roots = [
    context.docsGovernanceEnabled ? context.config.documentation.officialRoot : "",
    context.analysisGovernanceEnabled ? context.config.analysis.root || "analysis" : "",
    context.decisionsGovernanceEnabled ? context.config.decisions.root || "decisions" : "",
    context.taskPlansGovernanceEnabled ? context.config.taskPlans.root || "tasks" : "",
  ];
  const uniqueRoots = [...new Set(roots.filter((root) => root && pathExists(context.root, root)))];

  for (const root of uniqueRoots) {
    for (const file of walkFiles(context.root, root, (path) => /_index\.md$/i.test(path))) {
      const actual = file.split("/").at(-1) || "";
      const expected = expectedFolderIndexName(file);
      if (actual !== expected) {
        context.add(
          "error",
          "index-name",
          `Index file must be named after its folder: expected ${expected}, found ${actual}.`,
          file,
        );
      }
    }
  }
}

export function ensureFolderIndex(
  context: LintContext,
  indexPath: string,
  folderRoot: string,
  title: string,
  fileKind: string,
  pomKind: string,
): void {
  if (pathExists(context.root, indexPath)) return;

  const normalizedIndexPath = normalize(indexPath).replace(/\\/g, "/");
  const files = walkFiles(
    context.root,
    folderRoot,
    (path) => path.endsWith(".md") && normalize(path).replace(/\\/g, "/") !== normalizedIndexPath,
  ).sort((a, b) => a.localeCompare(b));

  const lines: string[] = [
    `# ${title}`,
    "",
    "Generated by `npm run pom:lint` when the configured folder index is missing.",
    "",
    `## ${fileKind}s`,
    "",
    `| ${fileKind} | Role |`,
    "|---|---|",
  ];

  if (files.length === 0) {
    lines.push("| _No documents yet._ | - |");
  } else {
    const indexDir = dirname(indexPath);
    const cleanRoot = normalize(folderRoot).replace(/\\/g, "/").replace(/\/$/, "");
    for (const file of files) {
      let link = relative(indexDir, file).replace(/\\/g, "/");
      if (!link.startsWith(".") && !link.startsWith("/")) {
        link = `./${link}`;
      }
      const label = file.startsWith(`${cleanRoot}/`) ? file.slice(cleanRoot.length + 1) : file;
      lines.push(`| [\`${label}\`](${link}) | ${pomKind} document. |`);
    }
  }

  lines.push("");

  const absolutePath = join(context.root, indexPath);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, lines.join("\n"));
}

export function isGeneratedGovernanceIndex(context: LintContext, path: string): boolean {
  const indexes = [
    configuredIndexPath(context.config.analysis.indexPath, context.config.analysis.root || "analysis"),
    configuredIndexPath(context.config.decisions.indexPath, context.config.decisions.root || "decisions"),
    configuredIndexPath(context.config.taskPlans.indexPath, context.config.taskPlans.root || "tasks"),
  ];

  return indexes.some(
    (indexPath) => normalize(path).replace(/\\/g, "/") === normalize(indexPath).replace(/\\/g, "/"),
  );
}
